OnlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('about/', include('about.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

checkout/urls.py
from django.urls import path

from .views import checkout, create_order, thank_you

app_name = 'checkout'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('create-order/', create_order, name='create_order'),
    path('thank-you/<int:order_id>/', thank_you, name='thank_you'),
]

store/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from store.models import Item


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='carts',
        verbose_name='Покупатель',
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания',)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    @property
    def total_price(self):
        total_price = sum(item.total_price for item in self.items.all())
        return total_price

    def __str__(self):
        return f"Cart {self.id} for {self.user.username}"

    def clear(self):
        self.items.all().delete()


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='Корзина',
    )
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        verbose_name='Товар',
    )
    quantity = models.PositiveIntegerField(
        default=1, verbose_name='Количество',)

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    @property
    def total_price(self):
        total_price = self.quantity * self.item.price
        return total_price

    def __str__(self):
        return f"{self.quantity} x {self.item.title}"

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from store.models import Item
from .models import Cart, CartItem


@login_required
def cart(request):
    """
    Представление для вывода всех объектов
    товаров корзины и самой корзины.
    """
    cart = Cart.objects.filter(user=request.user).first()

    if not cart:
        cart = Cart.objects.create(user=request.user)

    context = {
        'cart_items': CartItem.objects.filter(cart=cart),
        'cart': cart
    }

    return render(request, 'cart/cart.html', context)


@login_required
def add_to_cart(request, item_slug):
    """
    Представление для добавления товара в корзину
    либо увеличения его количества на 1.
    """
    item = get_object_or_404(Item, slug=item_slug)
    cart, _ = Cart.objects.get_or_create(user=request.user)

    cart_item, created = CartItem.objects.get_or_create(
        cart=cart,
        item=item
    )
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart:cart')


@login_required
def delete_cart_item(request, item_slug):
    """
    Представление для удаления объекта товара в корзине.
    """
    cart_item = CartItem.objects.get(
        cart=Cart.objects.get(user=request.user),
        item=get_object_or_404(Item, slug=item_slug)
    )
    cart_item.delete()
    return redirect('cart:cart')


@login_required
def update_cart_item(request):
    """
    Представление для обработки AJAX-запроса
    и последущего обновления БД и отправки на
    страницу JSON-ответа с необходимыми данными.
    """
    if request.method == 'POST' and request.is_ajax():
        cart_item_id = request.POST.get('cart_item_id')
        new_quantity = int(request.POST.get('new_quantity'))
        cart_id = int(request.POST.get('cart_id'))

        cart = Cart.objects.get(pk=cart_id)
        cart_item = get_object_or_404(CartItem, id=cart_item_id)
        cart_item.quantity = new_quantity
        cart_item.save()
        return JsonResponse({
            'success': True,
            'cart_item_id': cart_item.id,
            'cart_item_quantity': cart_item.quantity,
            'cart_item_total_price': cart_item.total_price,
            'cart_total_price': cart.total_price
        })
    else:
        return JsonResponse({
            'success': False, 'error': 'Invalid request method'
        })

templates/cart/cart.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "assets/css/cart.css"%}" />
{% endblock %}

{% block content %}
<h1>Корзина</h1>
{% if cart_items %}
  <section>
    <div class="table-wrapper">
      <table class="alt">
        <thead>
          <tr>
            <th>Название</th>
            <th>Количество</th>
            <th>Цена</th>
          </tr>
        </thead>
        <tbody>
          {% for cart_item in cart_items %}
          <tr>
            <td><a href="{% url 'store:item_details' cart_item.item.slug %}">{{ cart_item.item.title }}</a></td>
            <td>
                <div class="count">
                  <span class="minus">—</span>
                  <input type="number" value="{{ cart_item.quantity }}" class="quantity-input" data-cart-item-id="{{ cart_item.id }}">
                  <span class="plus">+</span>
                </div>
                <form id="update-cart-item-form" method="POST" action="{% url 'cart:update_cart_item' %}" style="display:none;">
                  {% csrf_token %}
                  <input type="hidden" id="new-quantity-input" name="new_quantity">
                  <input type="hidden" id="cart-item-id-input" name="cart_item_id">
                </form>
            </td>
            <td class="cart-item-total-price" data-cart-item-id="{{ cart_item.id }}">{{ cart_item.total_price }}</td>
            <td style="border: none; background-color: #ffffff;" align="center">
              <a href="{% url 'cart:delete_cart_item' cart_item.item.slug %}">
                <img src ="{% static "images/garbage.svg" %}" width="25" height="25" >
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td><u><b><span id="cart-total-price" data-cart-id="{{ cart.id }}">{{ cart.total_price }}</span></b></u></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </section>
  <div style="text-align: justify;">
    <a href="{% url 'store:home' %}" style="float: left;" class="button">Продолжить покупки</a>
    <a href="{% url 'checkout:checkout' %}" style="float: right;" class="button">Оформить заказ</a>
  </div>
{% else %}
  <p>Ваша корзина пуста.</p>
{% endif %}
{% block js %}
  <script src={% static "assets/js/ajax.js"%}></script>
{% endblock %}
{% endblock %}