OnlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('about/', include('about.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

about/urls.py
from django.urls import path

from .views import AboutAuthorView, AboutProjectView

app_name = 'about'

urlpatterns = [
    path('project/', AboutProjectView.as_view(), name='about_project'),
    path('me/', AboutAuthorView.as_view(), name='about_me'),
]

cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

news/urls.py
from django.urls import path

from .views import news, news_tag_list, news_tag_details, news_item_details

app_name = 'news'

urlpatterns = [
    path('', news, name='news'),
    path('news/categories/', news_tag_list, name='news_tag_list'),
    path('news/category-details/<slug:slug>/', news_tag_details, name='news_tag_details'),
    path('news/<slug:item_slug>/', news_item_details, name='news_item_details'),
]

store/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from .views import SignUp, feedback_processing, profile, user_orders

app_name = 'users'

urlpatterns = [
    path('orders/', user_orders, name='user_orders'),
    path('profile/', profile, name='profile'),
    path('feedback-processing/', feedback_processing, name='feedback_processing'),
    path(
        'auth/logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    path('auth/signup/', SignUp.as_view(), name='signup'),

    path(
        'auth/login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'auth/password_reset/',
        PasswordResetView.as_view(
            template_name='users/managment/password_reset_form.html',
            email_template_name='users/managment/password_reset_email.html',
            success_url='done/'),
        name='password_reset_form'
    ),

    path('auth/password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/managment/password_reset_done.html'),
         name='password_reset_done'),

    path('auth/reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/managment/reset_done.html'),
         name='reset_done'),

    path('auth/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/managment/password_reset_confirm.html',
             success_url=reverse_lazy('users:reset_done')),
         name='password_reset_confirm'),

    path(
        'auth/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/managment/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path(
        'auth/password_change/',
        PasswordChangeView.as_view(
            template_name='users/managment/password_change_form.html',
            success_url='done/'),
        name='password_change'
    ),
    path(
        'auth/password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/managment/password_change_done.html'),
        name='password_change_done'
    ),
]

templates/includes/footer.html
<footer id="footer">
    <div class="inner">
        <section>
            <h2>Оставлись вопросы? Свяжитесь с нами</h2>
            <form method="post" action="{% url 'users:feedback_processing'%}">
                {% csrf_token %}
                <div class="fields">
                    <div class="field half">
                        <input type="text" name="feedback_name" id="feedback_name" placeholder="Имя" />
                    </div>
                    <div class="field half">
                        <input type="email" name="feedback_email" id="feedback_email" placeholder="Почта" />
                    </div>
                    <div class="field">
                        <textarea name="feedback_message" id="feedback_message" placeholder="Сообщение"></textarea>
                    </div>
                </div>
                <ul class="actions">
                    <li><input type="submit" value="Отправить" class="primary" /></li>
                </ul>
            </form>
        </section>
        <section>
            <h2>Наши ресурсы</h2>
            <ul class="icons">
                <li><a href="mailto:info@sovizm.com" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
            </ul>
        </section>
    </div>
</footer>

templates/includes/header.html
{% load static %}
<header id="header">
    <div class="inner">
        <!-- Logo -->
        <a href="{% url 'store:home' %}" class="logo">
            <span class="symbol"><img src="{% static "images/logo.svg" %}" alt="" /></span><span class="title">СОВИЗМ</span>
        </a>
        <!-- Nav -->
        <nav>
            <ul>
                <li><a href="#menu">Menu</a></li>
            </ul>
            <br>
            <ul class="actions">
                <li>
                    <a href="{% url 'store:tag_list' %}">
                    <img src ="{% static "images/shop.png" %}" width="40" height="40" ></a>
                    <br>
                    <a href="{% url 'cart:cart' %}">
                    <img src ="{% static "images/cart.jpg" %}" width="40" height="40" ></a>
                    <br>
                    <a href="{% url 'users:profile' %}">
                    <img src ="{% static "images/profile.png" %}" width="40" height="40" ></a>
                    <br>
                     <a href="{% url 'news:news' %}">
                    <img src ="{% static "images/news.png" %}" width="40" height="40" ></a>
                </li>
            </ul>
        </nav>
    </div>
</header>
<!-- Menu -->
<nav id="menu">
    <h2>Меню</h2>
    <ul>
        <li><a href="{% url 'store:tag_list' %}">Все категории товаров и услуг</a></li>
        <li><a href="{% url 'news:news_tag_list' %}">Все категории новостей</a></li>
        <li><a href="{% url 'cart:cart' %}">Корзина</a></li>
        <li><a href="{% url 'users:profile' %}">Мой профиль</a></li>
        <li><a href="{% url 'about:about_me' %}">О нас</a></li>
    </ul>
</nav>

templates/includes/paginator.html
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}" class="button small">Prev</a>
{% else %}
  <a class="button small disabled">Prev</a>
{% endif %}
{% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
    <a href="#" class="button small disabled">{{ i }}</a>
  {% else %}
    <a href="?page={{ i }}" class="button small">{{ i }}</a>
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="button small">Next</a>
{% else %}
  <a class="button small disabled">Next</a>
{% endif %}