OnlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('about/', include('about.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

store/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
]

store/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from taggit.models import GenericTaggedItemBase, TagBase


class ItemTag(TagBase):
    image = models.ImageField(
        upload_to='categories/',
        verbose_name='Изображение',
        blank=True
    )
    description = models.TextField(
        blank=True,
        verbose_name='Описание',
        )

    class Meta:
        verbose_name = _("Категория")
        verbose_name_plural = _("Категории")


class TaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(
        ItemTag,
        on_delete=models.CASCADE,
        related_name="items",
        verbose_name='Категория',
    )


class Item(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название',)
    description = models.TextField(verbose_name='Описание',)
    slug = models.CharField(
        unique=True,
        max_length=50,
    )
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления',)
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Новая цена',
    )
    old_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Старая цена',
        blank=True,
        null=True,
    )
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='items/',
        blank=True,
    )
    is_available = models.BooleanField(
        default=True,
        verbose_name='Доступно',
    )
    tags = TaggableManager(through=TaggedItem, related_name="tagged_items", verbose_name='Категории',)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-price']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Item, ItemTag
from .paginator import paginator


def store(request):
    # items = Item.objects.filter(is_available=True)
    # context = {
    #     'page_obj': paginator(request, items, 9),
    #     'range': [*range(1, 7)],  # For random css styles
    # }
    #
    # return render(request, 'store/main_page.html', context)
    tags = ItemTag.objects.all()
    context = {
        'page_obj': paginator(request, tags, 6),
    }
    return render(request, 'store/tag_list.html', context)


def item_details(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    context = {
        'item': item,
    }
    return render(request, 'store/item_details.html', context)


def tag_details(request, slug):
    tag = get_object_or_404(ItemTag, slug=slug)
    items = Item.objects.filter(tags__in=[tag])
    context = {
        'tag': tag,
        'page_obj': paginator(request, items, 3),
    }
    return render(request, 'store/tag_details.html', context)


def tag_list(request):
    tags = ItemTag.objects.all()
    context = {
        'page_obj': paginator(request, tags, 6),
    }
    return render(request, 'store/tag_list.html', context)

templates/store/item_details.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<h2>{{ item.title }}</h2>
<p>Товар принадлежит к категории
{% for tag in item.tags.all %}
    <b><a href="{% url 'store:tag_details' tag.slug %}">{{ tag }}</a></b>
    {% if not forloop.last %},{% endif %}
{% endfor %}
</p>
{% if item.image %}
    <p><span class="image left"><img src="{{ item.image.url }}" alt="" style="width: 250px; height: 250px;"/>
{% else %}
    <p><span class="image left"><img src="{% static "images/pic14.jpg" %}" alt="" style="width: 250px; height: 250px;"/>
{% endif %}
    <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
        Добавить в корзину</a>
    </span>
        {% if item.old_price %}
    <p>Старая цена: <s>{{ item.old_price }} рублей</s>
    Новая цена: <b>{{ item.price }}</b> рублей </p>
{% else %}
    <p>Цена: <b>{{ item.price }}</b> рублей </p>
    </span>{% endif %}
    {{ item.description }}
</p>
<hr>
{% endblock %} 

templates/store/main_page.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<h1>OnlineStore: Онлайн-магазин для всех ваших потребностей<br /></h1>
<p>Мой проект - это современный интернет-магазин, который был разработан с использованием передовых технологий веб-разработки. Использовался язык программирования Python и его фреймворк Django для создания серверной части сайта.</p>
<p>Для создания пользовательского интерфейса были использованы языки HTML, CSS и JavaScript. Большее количество шаблонов было взято с <a href="http://html5up.net">HTML5 UP</a></p>
<p>Я также использовал SQLite для хранения данных, таких как информация о продуктах и заказах.</p>
<section class="tiles">
    {% for item in page_obj %}
    <article class="style{{ range|random }}">
        <span class="image">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt="" style="width: 353px; height: 326px;" />
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        </span>
        <a href="{% url 'store:item_details' item.slug %}">
            <div class="tag">
                <object> 
                    {% for tag in item.tags.all %}
                        <a href="{% url 'store:tag_details' tag.slug %}" style="color: white">{{ tag }}</a>
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </object><br />
            </div>
            <h2>{{ item.title }}</h2>
            <div class="content">
                <p>{{ item.description|truncatechars:150 }}</p>
            </div>
        </a>
    </article>
    {% endfor %}
</section>
{% endblock %} 

templates/store/tag_details.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <h2>{{ tag.name }}</h2>
    Количество товаров:&ensp;{{ tag.items.count }}
    <p><a href="{% url 'store:tag_list'%}"><b>Все категории</b></a></p>
    <hr>

{% for item in page_obj %}

    <div style="display:flex; flex-direction: row; justify-content: space-between">
<div>
    <p>
    <a href="{% url 'store:item_details' item.slug %}"><b>{{item.title}}</b></a>
</p>
<p>
    <span>{{ item.description|truncatechars:300 }}</span>
</p>
</div>


{% if tag.image %}
    <img class="image right" src="{{ tag.image.url }}" alt="" style="object-fit: cover; width:350px; heigth:350px" />
{% else %}
    <img src="{% static "images/pic14.jpg" %}" alt="" style="object-fit: cover;width:350px; heigth:350px" />
{% endif %}
</div>
        <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
            Добавить в корзину</a>

          {% if item.old_price %}
        <p>Старая цена: <s>{{ item.old_price }} рублей</s>
        Новая цена: <b>{{ item.price }}</b> рублей </p>
    {% else %}
        <p>Цена: <b>{{ item.price }}</b> рублей </p>
    {% endif %}

{% if not forloop.last %}<hr>{% endif %}

{% endfor %}
{% endblock %} 

templates/store/tag_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<h1>СОВИЗМ - современные измерения и не только! <br /></h1>
<p>Добро пожаловать, уважаемые коллеги!  </p>
<p>Наша организация на рынке более 3-х лет и мы хотели бы помочь Вашему бизнесу с оборудованием, метрологией, системами менеджмента качества и не только. </p>
<p>Вы можете ознакомиться с каталогом оборудования, которое мы можем Вам поставить в кратчайшие сроки и по приятной цене, а также услугами, оказываемыми нашими специалистами
    или просто оставьте заявку любым удобным способом. Наши сотрудники Вас проконсультируют в ближайшее время! </p>

<h2>Мы можем предложить</h2>
<!--<hr>-->
{% for tag in page_obj %}
    <hr>
    <div style="display:flex; flex-direction: row; justify-content: space-between">
<div>
    <p>
    <a href="{% url 'store:tag_details' tag.slug %}"><b>{{ tag.name }}</b></a>
</p>
<p>
    <span>{{tag.description|truncatechars:300}}</span><span></span>
</p>
</div>


{% if tag.image %}
    <img class="image right" src="{{ tag.image.url }}" alt="" style="object-fit: cover; width:350px; heigth:350px" />
{% else %}
    <img src="{% static "images/pic14.jpg" %}" alt="" style="object-fit: cover;width:350px; heigth:350px" />
{% endif %}
<!--{{tag.description}}{{tag.description}}-->
{% if not forloop.last %}<hr>{% endif %}
</div>
{% endfor %}
{% endblock %}