OnlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('about/', include('about.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from .views import SignUp, feedback_processing, profile, user_orders

app_name = 'users'

urlpatterns = [
    path('orders/', user_orders, name='user_orders'),
    path('profile/', profile, name='profile'),
    path('feedback-processing/', feedback_processing, name='feedback_processing'),
    path(
        'auth/logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    path('auth/signup/', SignUp.as_view(), name='signup'),

    path(
        'auth/login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'auth/password_reset/',
        PasswordResetView.as_view(
            template_name='users/managment/password_reset_form.html',
            email_template_name='users/managment/password_reset_email.html',
            success_url='done/'),
        name='password_reset_form'
    ),

    path('auth/password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/managment/password_reset_done.html'),
         name='password_reset_done'),

    path('auth/reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/managment/reset_done.html'),
         name='reset_done'),

    path('auth/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/managment/password_reset_confirm.html',
             success_url=reverse_lazy('users:reset_done')),
         name='password_reset_confirm'),

    path(
        'auth/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/managment/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path(
        'auth/password_change/',
        PasswordChangeView.as_view(
            template_name='users/managment/password_change_form.html',
            success_url='done/'),
        name='password_change'
    ),
    path(
        'auth/password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/managment/password_change_done.html'),
        name='password_change_done'
    ),
]

checkout/models.py
from django.contrib.auth.models import User
from django.db import models

from store.models import Item


class Order(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('cash_courier', 'Получить КП')
    ]
    STATUS_CHOICES = [
        ('created', 'Создан'),
        ('processing', 'Обрабатывается'),
        ('shipped', 'Отправлен'),
        ('delivered', 'Доставлен'),
        ('canceled', 'Отменен'),
    ]
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENT_METHOD_CHOICES,
        verbose_name='Способ оплаты',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Покупатель',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='created',
        verbose_name='Статус',
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-created_at']

    @property
    def total_price(self):
        total_price = sum(
            order_item.total_price for order_item in self.items.all())
        return total_price

    def __str__(self):
        return f"Заказ номер {self.id} для {self.user}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='Заказ',
    )
    item = models.ForeignKey(
        Item, on_delete=models.CASCADE, verbose_name='Товар',)
    quantity = models.PositiveIntegerField(
        default=1, verbose_name='Количество',)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Цена',)

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    @property
    def total_price(self):
        total_price = self.quantity * self.item.price
        return total_price

    def __str__(self):
        return f"{self.quantity} x {self.item.title} in Order {self.order.id}"


class ShippingAddress(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя',)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия',)
    email = models.EmailField(verbose_name='Почта',)
    phone = models.CharField(max_length=20, verbose_name='Телефон',)
    address_line_1 = models.CharField(max_length=200, verbose_name='Адрес',)
    address_line_2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Адрес (дополнительно)',)
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='shipping_address', verbose_name='Заказ',)

    class Meta:
        verbose_name = 'Адрес доставки'
        verbose_name_plural = 'Адреса доставки'

    def __str__(self):
        return f"""
        {self.address_line_1} {self.address_line_2}
        Для: {self.first_name} {self.last_name},
        Почта: {self.email},
        Телефон: {self.phone}
        """

users/models.py
from django.db import models


class Feedback(models.Model):
    feedback_name = models.CharField(max_length=50, verbose_name='Имя покупателя',)
    feedback_email = models.EmailField(verbose_name='Почта покупателя',)
    feedback_message = models.TextField(verbose_name='Текст',)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания',)

    class Meta:
        verbose_name = 'Обратная связь покупателя'
        verbose_name_plural = 'Обратная связь покупателя'

    def __str__(self):
        return self.feedback_message[:30]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Feedback

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['feedback_name', 'feedback_email', 'feedback_message']

users/views.py
import asyncio

import telegram
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from OnlineStore.settings import TELEGRAM_CHAT_ID, TELEGRAM_TOKEN
from checkout.models import Order
from .forms import CreationForm, FeedbackForm
from .models import Feedback


@login_required
def user_orders(request):
    """
    Представление списка заказов пользователя.
    """
    orders = Order.objects.filter(user=request.user)
    context = {
        'orders': orders,
    }
    return render(request, 'users/user_orders.html', context)


@login_required
def profile(request):
    """
    Представление профиля пользователя.
    """
    return render(request, 'users/profile.html')


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('store:home')
    template_name = 'users/signup.html'


async def send_telegram_message(message):
    """
    Асинхронная функция для отправки сообщения в ТГ.
    """
    bot = telegram.Bot(token=TELEGRAM_TOKEN)
    chat_id = TELEGRAM_CHAT_ID
    await bot.send_message(chat_id=chat_id, text=message)


def feedback_processing(request):
    """
    Представление приема и обработки для обратной связи.
    """
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = Feedback(
                feedback_name=form.cleaned_data['feedback_name'],
                feedback_email=form.cleaned_data['feedback_email'],
                feedback_message=form.cleaned_data['feedback_message'],
            )
            feedback.save()

            # Отпрака сообщения
            message = f"Обратная связь от {feedback.feedback_name} ({feedback.feedback_email}):\n {feedback.feedback_message}"
            asyncio.run(send_telegram_message(message))

            return render(request, 'users/feedback_success.html')
    return render(request, 'users/feedback_failed.html')

templates/users/feedback_failed.html
{% extends 'base.html' %}

{% block content %}
  <h1>Извините, Ваш отзыв был не обработан =(</h1>
  <p>К сожалению, Ваше сообщение не было обработано. Возможно, форма не была корректно заполнена.</p>
  <p>Если же Вы уверены что форма заполнена корректно, свяжитесь с нами по почте или по социальным сетям. Ссылки на них расположены внизу страницы.</p>
{% endblock %}

templates/users/feedback_success.html
{% extends 'base.html' %}

{% block content %}
  <h1>Спасибо за отзыв!</h1>
  <p>Ваше сообщение уже принято в обработку. В ближайшее время мы свяжемся с Вами.</p>
{% endblock %}

templates/users/logged_out.html
{% extends 'base.html' %}

{% block content %}
  <h1>Вы успешно вышли из системы</h1>
  <p>Вернуться на <a href="{% url 'users:login' %}">страницу входа</a>.</p>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
{% endblock %}

{% block content %}
<h1>Войти на сайт</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <p>
  <div class="form-field">
    <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
  </div>
  {% if form.errors %}
  <div class="alert alert-danger">
    {% for field, errors in form.errors.items %}
      {% for error in errors %}
        <span class="error-message">{{ error }}</span>
      {% endfor %}
    {% endfor %}
  </div>
{% endif %}
</p>
{% endfor %}
  <br>
  <button type="submit">Войти</button>
</form>
<div>
  Еще не зарегистрированы?
  <a href="{% url 'users:signup' %}">Зарегистрироваться</a>
</div>
<a href="{% url 'users:password_reset_form' %}">
  Забыли пароль?
</a>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Ваш профиль</h1>
<p>Здравствуйте, {{ request.user.get_username }}. Всего у вас <strong>{{ request.user.orders.count }}</strong> заказов.</p>
<p>Ваши заказы: <a href="{% url 'users:user_orders' %}">Перейти к заказам</a></p>
<p>Если вы хотите выйти из системы: <a href="{% url 'users:logout' %}">Выйти</a></p>
<p>Если вы хотите сменить пароль: <a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
{% endblock %}

{% block content %}
<h1>Зарегистрироваться</h1>
<form method="post" action="{% url 'users:signup' %}">
  {% csrf_token %}
  {% for field in form %}
  <p>
  <div class="form-field">
    <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
  </div>
  {% if form.errors %}
  <div class="alert alert-danger">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
  </div>
{% endif %}
</p>
{% endfor %}
  <button type="submit" class="btn btn-primary">
    Зарегистрироваться
  </button>
</form>
{% endblock %}

templates/users/user_orders.html
{% extends "base.html" %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "assets/css/profile.css"%}" />
{% endblock %}

{% block content %}
<h1>Ваши заказы</h1>
{% if orders %}
  {% for order in orders %}
  <div class="order-wrapper">
    <div class="order-header">
      <p>Адрес: {{ order.shipping_address }}</p>
      <p><strong>Статус заказа: {{ order.get_status_display }}</strong></p>
    </div>
      <div class="table-wrapper">
      <table class="alt">
        <thead>
          <tr>
            <th>Название</th>
            <th>Количество</th>
            <th>Цена</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in order.items.all %}
          <tr>
            <td>{{ order_item.item.title }}</td>
            <td>
                {{ order_item.quantity }}
            </td>
            <td>{{ order_item.total_price }}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td><b>{{ order.total_price }}</b></td>
          </tr>
        </tfoot>
      </table>
      </div>
    </div>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% else %}
  <p>У вас пока нет заказов.</p>
{% endif %}
{% endblock %} 